# fly.toml app configuration file generated for angular-dating-app-frosty-frog-9792 on 2023-11-27T15:55:11-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "angular-dating-app-frosty-frog-9792"
primary_region = "lax"

[build]
  image = "bperfetti/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dgwdyrmsn"
  CloudinarySettings__ApiKey="392446396335862"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
